syntax = "proto2";

package IHeart;

import "ProtoToMarkup/MarkupOptions.proto";
import "STSNowPlaying.proto";
import "STSPlayQueueIntrospect.proto";
import "IHeartLoginResponse.proto";
import "IHeartQueuedTrack.proto";
import "NowPlayingSupplement.proto";
import "Common.proto";

message ClientStats {
  optional uint64 txPkts = 1;
  optional uint64 rxPkts = 2;
  optional uint64 httpErrs = 3;
  optional uint64 serviceErrs = 4;
  optional uint64 parseErrs = 5;
  optional uint64 loginRetry = 6;
}

message IHeartIntrospectResponse {
  optional string stsServerIP = 1;
  optional .Common.Accounts accounts = 2;
  optional .IHeart.ClientStats clientStats = 3;
}

message IHeartAccountIntrospectResponse {
  optional string state = 1;
  optional .STS.NowPlaying nowPlaying = 2;
  optional .STS.PlayQueueIntrospect playQueue = 3;
  optional string groupId = 4;
  optional string myDeviceId = 5;
  optional string andoGUID = 6;
  optional uint32 marketId = 7;
  optional .IHeart.LoginResponse loginResponse = 8;
  optional uint32 transactionId = 9;
  optional .IHeart.QueuedTrack playingItem = 10;
  optional .IHeart.NowPlayingSupplement nowPlayingSupplement = 11;
  optional .IHeart.ClientStats clientStats = 12;
}
