syntax = "proto2";

package LocalMusic;

import "ProtoToMarkup/MarkupOptions.proto";
import "LocalMusicTrackInfo.proto";
import "LocalMusicError.proto";
import "Common.proto";

message pageLinks {
  optional .Common.Link self = 1;
  optional .Common.Link previous = 2;
  optional .Common.Link next = 3;
  optional .Common.Link first = 4;
  optional .Common.Link last = 5;
}

message embeddedTracks {
  repeated .LocalMusic.TrackInfo tracks = 1;
  repeated .LocalMusic.TrackInfo episodes = 2;
}

message Tracks {
  optional int64 count = 1;
  optional int64 total = 2;
  optional .LocalMusic.embeddedTracks _embedded = 3;
  optional .LocalMusic.error error = 4;
  optional .LocalMusic.pageLinks _links = 5;
}
