syntax = "proto2";

enum KEY_VALUE {
  KEY_VAL_PLAY = 0;
  KEY_VAL_PAUSE = 1;
  KEY_VAL_STOP = 2;
  KEY_VAL_PREV_TRACK = 3;
  KEY_VAL_NEXT_TRACK = 4;
  KEY_VAL_THUMBS_UP = 5;
  KEY_VAL_THUMBS_DOWN = 6;
  KEY_VAL_BOOKMARK = 7;
  KEY_VAL_POWER = 8;
  KEY_VAL_MUTE = 9;
  KEY_VAL_VOLUME_UP = 10;
  KEY_VAL_VOLUME_DOWN = 11;
  KEY_VAL_PRESET_1 = 12;
  KEY_VAL_PRESET_2 = 13;
  KEY_VAL_PRESET_3 = 14;
  KEY_VAL_PRESET_4 = 15;
  KEY_VAL_PRESET_5 = 16;
  KEY_VAL_PRESET_6 = 17;
  KEY_VAL_AUX_INPUT = 18;
  KEY_VAL_SHUFFLE_OFF = 19;
  KEY_VAL_SHUFFLE_ON = 20;
  KEY_VAL_REPEAT_OFF = 21;
  KEY_VAL_REPEAT_ONE = 22;
  KEY_VAL_REPEAT_ALL = 23;
  KEY_VAL_PLAY_PAUSE = 24;
  KEY_VAL_ADD_FAVORITE = 25;
  KEY_VAL_REMOVE_FAVORITE = 26;
  KEY_VAL_BLUETOOTH = 27;
  INVALID_KEY = 28;
}

enum KEY_STATE {
  KEY_STATE_PRESSED = 0;
  KEY_STATE_RELEASED = 1;
  KEY_STATE_REPEAT = 2;
  KEY_STATE_PnH = 3;
  KEY_STATE_XPnH = 4;
  KEY_STATE_TIMEOUT = 5;
  KEY_STATE_INVALID = 6;
}

enum KEY_PRODUCER {
  KEY_PRODUCER_GABBO = 0;
  KEY_PRODUCER_CONSOLE = 1;
  KEY_PRODUCER_IR_REMOTE = 2;
  KEY_PRODUCER_LIGHTSWITCH_REMOTE = 3;
  KEY_PRODUCER_ETAP = 4;
  KEY_PRODUCER_BOSELINK_REMOTE = 5;
  KEY_PRODUCER_INVALID = 6;
}

enum ROOM_NUMBER {
  ROOM_A = 0;
  ROOM_ALL_ROOMS = 1;
  NUM_ROOMS = 1;
}

enum ZONE_ID {
  ZONE_1 = 0;
  ZONE_2 = 1;
  NUM_ZONES = 2;
  ALL_ZONES = 15;
}
