syntax = "proto2";

message SoftwareUpdateStart {
  optional string url = 1 [default = ""];
  optional uint32 update_crc = 2 [default = 0];
  optional uint32 update_size = 3 [default = 0];
  optional bool force = 4 [default = false];
}

message SoftwareUpdateValidateRequest {
  optional string install_xml_path = 1 [default = ""];
}

message SoftwareUpdateValidateStatus {
  optional bool success = 1;
}

message SoftwareUpdateAbort {
}

message SoftwareUpdateDataRequest {
  optional int32 byte_count = 1;
}

message SoftwareUpdateDataResponse {
  optional int32 byte_count = 1;
  optional bytes data = 2;
  optional bool endofstream = 3;
}
