syntax = "proto2";

package STS.MenuType;

enum Enum {
  locales = 1;
  recents = 2;
  favAlbums = 3;
  favArtists = 4;
  favPlaylists = 5;
  favTracks = 6;
  charts = 7;
  recommendations = 8;
  favoriteStations = 9;
  recentStations = 10;
  customStations = 11;
  international = 12;
  states = 13;
  cities = 14;
  local = 15;
  newsTalk = 16;
  publicRadio = 17;
  sportsRadio = 18;
  mixVariety = 19;
  genres = 20;
  liveStations = 21;
  talk = 22;
  createStation = 23;
  radioStations = 24;
  tracklistRadio = 25;
  forYou = 26;
  perfectFor = 27;
  tracklist = 28;
}
