syntax = "proto2";

package STS;

enum STSMsgId {
  STS_MSG_ID_SELECT_CONTENT_ITEM = 1;
  STS_MSG_ID_PLAY = 2;
  STS_MSG_ID_PAUSE = 3;
  STS_MSG_ID_STOP = 4;
  STS_MSG_ID_PLAYTOGGLE = 5;
  STS_MSG_ID_SHUFFLE = 6;
  STS_MSG_ID_SHUFFLE_OFF = 7;
  STS_MSG_ID_SHUFFLE_ON = 8;
  STS_MSG_ID_REPEAT = 9;
  STS_MSG_ID_REPEAT_OFF = 10;
  STS_MSG_ID_REPEAT_ONE = 11;
  STS_MSG_ID_REPEAT_ALL = 12;
  STS_MSG_ID_LIKE = 13;
  STS_MSG_ID_DISLIKE = 14;
  STS_MSG_ID_SKIP_NEXT = 15;
  STS_MSG_ID_SKIP_PREVIOUS = 16;
  STS_MSG_ID_AUDIO_STATUS = 17;
  STS_MSG_ID_VOLUME_STATUS = 18;
  STS_MSG_ID_NETWORK_STATUS = 19;
  STS_MSG_ID_MUTE_STATUS = 20;
  STS_MSG_ID_ADD_FAVORITE = 21;
  STS_MSG_ID_REMOVE_FAVORITE = 22;
  STS_MSG_ID_PLAYBACK = 23;
  STS_MSG_ID_PUSH_ACCOUNT_SETTINGS = 24;
  STS_MSG_ID_SSDP_DISCOVERY_STATUS = 25;
  STS_MSG_ID_SKIP_PREVIOUS_FORCE = 26;
  STS_MSG_ID_POWER_OFF = 27;
  STS_MSG_ID_SEEK_TO_TIME = 28;
  STS_MSG_ID_NOW_PLAYING_CHANGE = 65;
  STS_MSG_ID_ERRORS = 66;
  STS_MSG_ID_SELECT = 67;
  STS_MSG_ID_DESELECT = 68;
  STS_MSG_ID_AUDIO_SET_URL = 69;
  STS_MSG_ID_AUDIO_PLAY = 70;
  STS_MSG_ID_AUDIO_PAUSE = 71;
  STS_MSG_ID_AUDIO_STOP = 72;
  STS_MSG_ID_VOLUME_CONTROL = 73;
  STS_MSG_ID_RECENT = 74;
  STS_MSG_ID_MUTE_CONTROL = 75;
  STS_MSG_ID_STATUS = 76;
  STS_MSG_ID_SSDP_DISCOVERY_UPDATE = 77;
  STS_MSG_ID_SOURCE_DISCOVERY_STATUS = 78;
  STS_MSG_ID_ENABLE_VOLUME_STATUS = 79;
  STS_MSG_ID_NOW_PLAYING = 129;
  STS_MSG_ID_NAVIGATE = 130;
  STS_MSG_ID_SEARCH = 131;
  STS_MSG_ID_LOGIN = 132;
  STS_MSG_ID_ACTIVATE = 133;
  STS_MSG_ID_DEACTIVATE = 134;
  STS_MSG_ID_ACCOUNT_SETTINGS_REQUEST = 135;
  STS_MSG_ID_SET_ACCOUNT_SETTING_REQUEST = 136;
  STS_MSG_ID_ACCOUNT_SETTINGS_UPDATE = 137;
  STS_MSG_ID_UPDATE_SECRET = 138;
  STS_MSG_ID_SSDP_DISCOVERY_REGISTER = 139;
  STS_MSG_ID_SSDP_DISCOVERY_UNREGISTER = 140;
  STS_MSG_ID_AUTH_SERVER_INFO = 141;
  STS_MSG_ID_PROTOCOL_VERSION = 193;
  STS_MSG_ID_REGISTER_SERVICE = 194;
  STS_MSG_ID_SERVICE_INFO = 195;
  STS_MSG_ID_FLEX_UI = 196;
  STS_MSG_ID_CREATE_ACCOUNT = 198;
  STS_MSG_ID_RECREATE_ACCOUNT = 199;
  STS_MSG_ID_REMOVE_ACCOUNT = 200;
  STS_MSG_ID_CREATE_ACCOUNT_PROXY = 192;
  STS_MSG_ID_INTROSPECT = 202;
  STS_MSG_ID_ZEROCONF_REGISTER_SERVICE = 203;
  STS_MSG_ID_ZEROCONF_UNREGISTER_SERVICE = 204;
  STS_MSG_ID_DEVICE_INFO = 205;
  STS_MSG_ID_OAUTH_CREDENTIALS = 206;
  STS_MSG_ID_LOG_AUTOMATION = 207;
  STS_MSG_ID_STATION_INFO = 208;
  STS_MSG_ID_STREAMING_QUALITY = 209;
  STS_MSG_ID_GET_SERVICE_SETTINGS = 210;
  STS_MSG_ID_UPDATE_SERVICE_SETTINGS = 211;
}

message LoginRequest {
  required string account = 1;
  optional string password = 2;
  optional string accessToken = 3;
}

message LoginResponse {
  required bool success = 1;
}
