# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AudioServerMsgAudioData.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'AudioServerMsgAudioData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x41udioServerMsgAudioData.proto\"\x92\x01\n$AudioServerMsgAcceptAudioDataRequest\x12\x12\n\nbyte_count\x18\x01 \x01(\x05\x12\x13\n\x0b\x62yte_offset\x18\x03 \x01(\r\x12\x16\n\x0e\x62yte_offset_64\x18\x04 \x01(\x04\x12\x16\n\x0emin_byte_count\x18\x05 \x01(\x05\x12\x11\n\tstream_id\x18\x06 \x01(\r\"\xb2\x02\n\x1d\x41udioServerMsgAcceptAudioData\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x13\n\x0b\x65ndofstream\x18\x06 \x01(\x08\x12\x13\n\x0b\x62yte_offset\x18\x08 \x01(\r\x12\x1e\n\x0fslave_underflow\x18\t \x01(\x08:\x05\x66\x61lse\x12L\n\x0f\x65ncryption_type\x18\x0b \x01(\x0e\x32-.AudioServerMsgAcceptAudioData.EncryptionType:\x04NONE\x12\x16\n\x0e\x62yte_offset_64\x18\x0c \x01(\x04\x12\x11\n\tstream_id\x18\r \x01(\r\"@\n\x0e\x45ncryptionType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04NONE\x10\x01\x12\x0e\n\nOBFUSCATED\x10\x02\x12\x07\n\x03\x41\x45S\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AudioServerMsgAudioData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATAREQUEST']._serialized_start=34
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATAREQUEST']._serialized_end=180
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATA']._serialized_start=183
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATA']._serialized_end=489
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATA_ENCRYPTIONTYPE']._serialized_start=425
  _globals['_AUDIOSERVERMSGACCEPTAUDIODATA_ENCRYPTIONTYPE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
