# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: IPCMessageEnvelopeBase.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'IPCMessageEnvelopeBase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cIPCMessageEnvelopeBase.proto\"\x8d\x03\n\x16IPCMessageEnvelopeBase\x12\x43\n\x08msg_type\x18\x01 \x02(\x0e\x32\x1f.IPCMessageEnvelopeBase.MsgType:\x10MSG_TYPE_UNKNOWN\x12Q\n\rmsg_module_id\x18\x02 \x02(\x0e\x32#.IPCMessageEnvelopeBase.MsgModuleId:\x15MSG_MODULE_ID_UNKNOWN\x12\x11\n\x06msg_id\x18\x03 \x02(\x05:\x01\x30\x12\x14\n\x0cmsg_contents\x18\x06 \x02(\x0c\x12\x10\n\x08sequence\x18\x07 \x01(\r\x12\x14\n\x0cmsg_typename\x18\x08 \x01(\t\"`\n\x07MsgType\x12\x14\n\x10MSG_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0eMSG_TYPE_EVENT\x10\x01\x12\x14\n\x10MSG_TYPE_REQUEST\x10\x02\x12\x15\n\x11MSG_TYPE_RESPONSE\x10\x03\"(\n\x0bMsgModuleId\x12\x19\n\x15MSG_MODULE_ID_UNKNOWN\x10\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IPCMessageEnvelopeBase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPCMESSAGEENVELOPEBASE']._serialized_start=33
  _globals['_IPCMESSAGEENVELOPEBASE']._serialized_end=430
  _globals['_IPCMESSAGEENVELOPEBASE_MSGTYPE']._serialized_start=292
  _globals['_IPCMESSAGEENVELOPEBASE_MSGTYPE']._serialized_end=388
  _globals['_IPCMESSAGEENVELOPEBASE_MSGMODULEID']._serialized_start=390
  _globals['_IPCMESSAGEENVELOPEBASE_MSGMODULEID']._serialized_end=430
# @@protoc_insertion_point(module_scope)
