syntax = "proto2";

package SoundTouchInterface;

import "ProtoToMarkup/MarkupOptions.proto";

enum ErrorType {
  NO_ERROR = 0;
  HTTP_STATUS_BAD_REQUEST = 400;
  HTTP_STATUS_UNAUTHORIZED = 401;
  HTTP_STATUS_FORBIDDEN = 403;
  HTTP_STATUS_CONFLICT = 409;
  HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415;
  HTTP_STATUS_TOO_MANY_REQUESTS = 429;
  UNKNOWN_ERROR = 1000;
  UNASSOCIATED_DEVICE_ERROR = 1001;
  TIMEOUT_TO_MARGE_ERROR = 1002;
  CLIENT_JSON_ERROR = 1003;
  SERVER_JSON_ERROR = 1004;
  UNKNOWN_SOURCE_ERROR = 1005;
  PANDORA_TIMEOUT_ERROR = 1006;
  PANDORA_LOGIN_ERROR = 1007;
  GENERAL_PANDORA_ERROR = 1008;
  PANDORA_GEO_RESTRICTION_ERROR = 1009;
  DLNA_NOT_PLAYABLE_ERROR = 1013;
  UNKNOWN_ITEM_ERROR = 1014;
  DATA_PARSE_ERROR = 1016;
  MAINTANENCE_ERROR = 1017;
  PANDORA_SKIP_LIMIT_ERROR = 1018;
  CLIENT_XML_ERROR = 1019;
  OBSOLETE_1 = 1020;
  PANDORA_READ_ONLY_MODE = 1021;
  MARGE_SET_CRED_FAILED = 1022;
  INVALID_SOURCE_TYPE = 1023;
  SOURCE_ALREADY_EXISTS = 1024;
  SERVER_XML_ERROR = 1025;
  WEB_PAGE_EXPIRED_ERROR = 1027;
  SOURCE_LOGIN_ERROR = 1028;
  UNKNOWN_ACTION_ERROR = 1029;
  DEPRECATION_ERROR = 1030;
  ACTION_FAILED_FROM_LOGIN_ERROR = 1031;
  PANDORA_UNABLE_TOSET_STATION_LIST_ERROR = 1032;
  PANDORA_UNEXPECTED_STATION_CHECKSUM_ERROR = 1033;
  MARGE_REMOVE_CRED_FAILED = 1034;
  WIFI_PROFILE_SETUP_FAILED = 1035;
  UNABLE_TO_PROCESS_NOT_LOGGED_IN = 1036;
  DEVICE_UNABLE_TO_RESPOND_NOT_READY = 1037;
  SET_MARGE_ACCOUNT_ERROR = 1038;
  MARGE_SET_RECENTS_ERROR = 1039;
  END_OF_TRACKLIST = 1040;
  SOURCE_DISCONNECTED = 1041;
  ERROR_ACCESSING_VOLUME = 1042;
  EVENT_IN_WRONG_STATE = 1043;
  INFO_NOT_AVAILABLE = 1044;
  SELECT_ITEM_IN_WRONG_STATE = 1045;
  ALLEGROWEBSERVER_TIMEOUT = 1046;
  SOURCE_ALREADY_REMOVED = 1047;
  INVALID_PARAMETER_VALUE = 1048;
  SKIP_UNAVAILABLE_AT_LAST_TRACK = 1049;
  CANNOT_SET_SYSTEM_DATE_TIME = 1050;
  ETHERNET_CABLE_CONNECTED = 1051;
  MARGE_HTTP_ERROR = 1200;
  MARGE_NOT_SYNCHRONIZED = 1201;
  MARGE_CONNECTION_ERROR = 1202;
  MUSIC_SERVICE_COULD_NOT_CONNECT = 1300;
  MUSIC_SERVICE_PARSE_ERROR = 1301;
  MUSIC_SERVICE_API_ERROR = 1302;
  MUSIC_SERVICE_EMPTY_RESPONSE = 1303;
  MUSIC_SERVICE_WRONG_STATE_NAVIGATE_REQUEST = 1304;
  MUSIC_SERVICE_WRONG_STATE_SEARCH_REQUEST = 1305;
  MUSIC_SERVICE_WRONG_STATE_NOW_PLAYING_REQUEST = 1306;
  MUSIC_SERVICE_WRONG_STATE_ACTIVATE_REQUEST = 1307;
  MUSIC_SERVICE_WRONG_STATE_DEACTIVATE_REQUEST = 1308;
  MUSIC_SERVICE_ACCOUNT_LOGIN_FAILED = 1309;
  MUSIC_SERVICE_ACCOUNT_ALREADY_EXISTS = 1310;
  MUSIC_SERVICE_ACCOUNT_LOGIN_AUTHENTICATION_FAILED = 1311;
  MUSIC_SERVICE_ACCOUNT_NOT_AVAILABLE = 1312;
  MUSIC_SERVICE_SKIP_LIMIT = 1313;
  MUSIC_SERVICE_NEXT_TRACK_NOT_PLAYABLE = 1314;
  MUSIC_SERVICE_UNPLAYABLE_TRACK = 1315;
  MUSIC_SERVICE_RATING_REQUEST_ERROR = 1316;
  MUSIC_SERVICE_LICENSE_DISALLOW = 1317;
  MUSIC_SERVICE_NO_PREV_TRACK = 1318;
  MUSIC_SERVICE_NO_NEXT_TRACK = 1319;
  MUSIC_SERVICE_ENDLESS_CONTEXT = 1320;
  MUSIC_SERVICE_UNKNOWN_ERROR = 1321;
  MUSIC_SERVICE_ADVERTISEMENT_DISALLOW = 1322;
  MUSIC_SERVICE_MISSING_SECRET = 1323;
  PANDORA_MAX_STATIONS_REACHED = 1400;
  PANDORA_DELETE_STATION_ERROR = 1401;
  PANDORA_NO_STATION_SPECIFIED = 1402;
  PANDORA_ACCOUNT_SUSPENDED = 1403;
  PANDORA_TRACK_UNRATEABLE = 1404;
  PANDORA_STATION_IS_INVALID = 1405;
  PANDORA_PLAYLIST_REQUEST_FAILED = 1406;
  PANDORA_INTERNAL_ERROR = 1407;
  PANDORA_THUMBS_IN_WRONG_STATE = 1408;
  STORED_MUSIC_OK = 0;
  STORED_MUSIC_UNKNOWN = 1600;
  STORED_MUSIC_ALLEGRO_WRAPPER_TIMEOUT = 1601;
  STORED_MUSIC_CONTROLLER_ACTION_FAILED = 1602;
  STORED_MUSIC_RENDERER_ACTION_TIMEOUT = 1603;
  STORED_MUSIC_RENDERER_BAD_FORMAT = 1604;
  STORED_MUSIC_RENDERER_NO_CONTENT = 1605;
  STORED_MUSIC_RENDERER_OTHER_SOAP_ERROR = 1606;
  STORED_MUSIC_SERVER_NO_RESPONSE = 1607;
  STORED_MUSIC_SERVER_NOT_FOUND = 1608;
  STORED_MUSIC_ALLEGRO_NOT_RUNNING = 1609;
  STORED_MUSIC_ITEM_NOT_SPECIFIED = 1610;
  STORED_MUSIC_SERVER_NOT_SPECIFIED = 1611;
  STORED_MUSIC_REQUESTED_COUNT_ZERO = 1612;
  STORED_MUSIC_NOT_CONTAINER_NOR_TRACK = 1613;
  STORED_MUSIC_EMPTY_CONTAINER = 1614;
  STORED_MUSIC_METADATA_NOT_FOUND = 1615;
  STORED_MUSIC_SKIP_NOT_SUPPORTED = 1616;
  STORED_MUSIC_TRANSPORT_CMD_TIMEOUT = 1617;
  STORED_MUSIC_RENDERER_NOT_AVAILABLE = 1618;
  STORED_MUSIC_SOURCE_NOT_ACTIVATED = 1619;
  STORED_MUSIC_SERVER_IS_INDEXING = 1620;
  STORED_MUSIC_SERVER_OTHER_SOAP_ERROR = 1621;
  STORED_MUSIC_UNKNOWN_CMD = 1641;
  STORED_MUSIC_MISSING_ACCOUNT = 1642;
  STORED_MUSIC_MISSING_CONTENT_ITEM = 1643;
  STORED_MUSIC_UNKNOWN_ACCOUNT = 1644;
  STORED_MUSIC_UNKNOWN_KEY = 1645;
  STORED_MUSIC_FAIL_TO_GET_PLAY_STATE = 1646;
  STORED_MUSIC_NO_SUCH_ITEM = 1647;
  STORED_MUSIC_SERVER_ACTION_FAILED = 1648;
  STORED_MUSIC_RECOVERABLE_PLAYBACK_FAILURE = 1649;
  STORED_MUSIC_AP_UNKNOWN = 1650;
  STORED_MUSIC_AP_BAD_URL = 1651;
  STORED_MUSIC_AP_DECODER = 1652;
  STORED_MUSIC_AP_UNDERRUN = 1653;
  STORED_MUSIC_AP_TIMEOUT = 1654;
  STORED_MUSIC_AP_BAD_MEDIA_PLAYLIST = 1655;
  STORED_MUSIC_UNSUPPORTED_SEARCH_TYPE = 1656;
  STORED_MUSIC_LOGIN_ERROR = 1691;
  HTTP_POST_NOT_FOUND = 1500;
  HTTP_GET_NOT_FOUND = 1501;
  HTTP_METHOD_NOT_ALLOWED = 1502;
  HTTP_NOT_FOUND = 1503;
  HTTP_NO_SERVER = 1504;
  MARGE_UNAUTHORIZED_ERROR = 1003;
  MARGE_WRONG_PASSWORD_ERROR = 1004;
  MARGE_ACCOUNT_NOT_FOUND = 5003;
  MARGE_MALFORMED_EMAIL_ERROR = 5004;
  MARGE_MALFORMED_PASSWORD_ERROR = 5005;
  MARGE_DUPLICATE_SOURCE_NAME = 5006;
  MARGE_RESOURCE_NOT_FOUND = 5007;
  MARGE_GENERIC_ERROR = 5008;
  MARGE_ACCOUNT_EXISTS_ERROR = 2006;
  LIGHTSWITCH_PAIRING_FAILED_ERROR = 2007;
  CANCEL_PAIR_LIGHTSWITCH_FAILED_ERROR = 2012;
  LIGHTSWITCH_ALREADY_PAIRED_ERROR = 2008;
  LIGHTSWITCH_UPDATING = 2013;
  BAD_BLUETOOTH_CHIP = 2014;
  WEBSOCKET_SERVER_OVERFLOW = 2009;
  WEBSOCKET_UNKNOWN_MESSAGE = 2010;
  WEBSOCKET_CURL_ERROR = 2011;
  WEBSOCKET_API_NOT_REGISTERED = 2015;
  WEBSOCKET_HANDLER_NOT_READY = 2016;
  WEBSOCKET_WRONG_SCOPE = 2017;
  FRONTDOOR_INVALID_MSGTYPE = 2018;
  CONTENT_ITEM_SELECT_TO_MULTIROOM_MASTER_FAILED = 3000;
  OPERATION_NOT_COMPLETED_NOT_MASTER = 3001;
  OPERATION_NOT_COMPLETED_UNSUPPORTED_ACTION = 3002;
  OPERATION_NOT_COMPLETED_NOT_IN_ZONE_MODE = 3003;
  AUDIO_ERROR_UNKNOWN = 3100;
  AUDIO_ERROR_BAD_URL = 3101;
  AUDIO_ERROR_DECODER = 3102;
  AUDIO_ERROR_TIMEOUT = 3103;
  AUDIO_ERROR_BAD_MEDIA_PLAYLIST = 3104;
  HELLO_USER_LOGGED_OUT = 3201;
  DEEZER_1_UNKNOWN_ERROR = 3301;
  DEEZER_4_REQUEST_LIMIT_REACHED = 3304;
  DEEZER_200_ACCESS_DENIED = 3320;
  DEEZER_300_NONEXISTENT_TOKEN = 3330;
  DEEZER_401_REQUEST_LIMIT_REACHED = 3341;
  DEEZER_500_INVALID_PARAMETER = 3350;
  DEEZER_501_MISSING_PARAMETER = 3351;
  DEEZER_600_INVALID_QUERY = 3360;
  DEEZER_800_REQUESTED_DATA_UNAVAILABLE = 3380;
  DEEZER_801_DATA_ALREADY_EXISTS = 3381;
  DEEZER_INSUFFICIENT_ACCOUNT_PRIVILEGES = 3390;
  DEEZER_30_SECOND_PREVIEW_ONLY = 3391;
  DEEZER_ACCOUNT_UNAVAILABLE = 3392;
  DEEZER_RADIO_STATION_UNAVAILABLE = 3393;
  DEEZER_TOO_MANY_FAVORITES = 3394;
  SPOTIFYCONNECT_NOT_ENABLED_LOGIN_FAILED = 3401;
  SPOTIFY_PREMIUM_ACCOUNT_EXPIRED = 3402;
  SPOTIFY_WEB_CLIENT_ERROR = 3403;
  SPOTIFY_UNKNOWN_PLAYBACK_CONTENT = 3404;
  IHEART_SERVICE_UNAVAILABLE = 3500;
  IHEART_USER_LOGGED_OUT = 3501;
  IHEART_NOT_FOUND = 3502;
  IHEART_NOT_ACTIVE_STREAMER = 3503;
  IHEART_NOT_VALID_FOR_STREAMING = 3504;
  IHEART_TRACK_CANNOT_BE_PLAYED = 3505;
  IHEART_CUSTOM_RADIO_IS_DISABLED = 3506;
  IHEART_NO_SCANS_AVAILABLE = 3507;
  IHEART_INVALID_CODE = 3508;
  IHEART_TOO_MANY_FAVORITES = 3509;
  IHEART_TOO_MANY_CUSTOM_STATIONS = 3510;
  IHEART_SKIP_LIMIT_REACHED = 3511;
  IHEART_INVALID_HOST = 3512;
  IHEART_INVALID_USER_OR_PW = 3513;
  IHEART_INVALID_DATE = 3514;
  IHEART_EMPTY_DEVICE_ID_OR_NAME = 3515;
  IHEART_INVALID_DEVICE = 3516;
  IHEART_BAD_REQUEST = 3517;
  IHEART_INVALID_HASH = 3518;
  IHEART_DEVICE_ALREADY_REGISTERED = 3519;
  IHEART_ACTIVITY_EXPIRED = 3520;
  BLUETOOTH_USER_LOGGED_OUT = 3701;
  QQMUSIC_UNKNOWN_ERROR = 3801;
  QQMUSIC_NO_ERROR = 3802;
  QQMUSIC_PARAMETER_ERROR = 3803;
  QQMUSIC_USER_HAS_NO_OTHER_ACCOUNT = 3804;
  QQMUSIC_ILLEGAL_OPERATION = 3805;
  QQMUSIC_SERVER_BUSY = 3806;
  QQMUSIC_USER_NOT_LOGIN = 3807;
  QQMUSIC_ACCOUNT_FREEZE = 3808;
  QQMUSIC_ACCOUNT_NOT_SUFFICIENT_FUND = 3809;
  QQMUSIC_USER_NOT_OPEN_TENCENT_FRIEND = 3810;
  QQMUSIC_USER_NOT_OPEN_QQ_ACCOUNT = 3811;
  QQMUSIC_CDKEY_NOT_EXIST = 3812;
  QQMUSIC_USER_CDKEY_NOT_BUNDLED = 3813;
  QQMUSIC_ACTIVITY_RESTRICTED = 3814;
  QQMUSIC_LOGIN_AUTHENTICATION_FAILED = 3815;
  QQMUSIC_INVALID_REQUEST = 3816;
  QQMUSIC_APPID_NOT_EXIST = 3817;
  QQMUSIC_NO_API_ACCESS_AUTHORIZATION = 3818;
  QQMUSIC_NO_IP_AUTHORIZATION = 3819;
  QQMUSIC_SIGNATURE_AUTHENTICATION_FAILED = 3820;
  QQMUSIC_VISIT_LIMIT_REACHED = 3821;
  QQMUSIC_ILLEGAL_INTERNET_PROTOCOL = 3822;
  QQMUSIC_REQUEST_NOT_ACCEPTED = 3823;
  QQMUSIC_API_NOT_EXIST = 3824;
  QQMUSIC_WRONG_ASSIGNED_OPENID = 3825;
  QQMUSIC_OPENAPI_NOT_AUTHORIZED = 3826;
  QQMUSIC_ACCESS_TOKEN_EXPIRED = 3827;
  QQMUSIC_ILLEGAL_OPENID = 3828;
  QQMUSIC_ILLEGAL_OPENKEY = 3829;
  QQMUSIC_OPENID_OR_OPENKEY_AUTHENTICATION_FAILED = 3830;
  QQMUSIC_OPENAPI_ERROR_RATE_EXCEEDS_58LIMIT = 3831;
  QQMUSIC_OPENAPI_ERROR_RATE_EXCEEDS_60LIMIT = 3832;
  QQMUSIC_OPENAPI_ERROR_RATE_EXCEEDS_65LIMIT = 3833;
  QQMUSIC_OPENID_OPENKEY_NOT_MATCHED = 3834;
  QQMUSIC_PASSWORD_CHANGED = 3835;
  QQMUSIC_RESERVED = 3836;
  QQMUSIC_REQUIRED_FIELD_NOT_SENT = 3837;
  QQMUSIC_WRONG_PARAM_FORMAT = 3838;
  QQMUSIC_RETURNED_PACKAGE_FORMAT_ERROR = 3839;
  QQMUSIC_SIGNATURE_FAILED = 3840;
  QQMUSIC_NETWORK_ERROR = 3841;
  QQMUSIC_NOT_ENABLED_LOGIN_FAILED = 3842;
  SIRIUSXM_UNKNOWN_ERROR = 3900;
  SIRIUSXM_NETWORK_ERROR = 3901;
  SIRIUSXM_CONFIGURATION_ERROR = 3902;
  SIRIUSXM_AUTHENTICATION_INITIATION_ERROR = 3903;
  SIRIUSXM_AUTHENTICATION_COMPLETION_ERROR = 3904;
  SIRIUSXM_TOKEN_REQUEST_ERROR = 3905;
  SIRIUSXM_TOKEN_UPDATE_ERROR = 3906;
  SIRIUSXM_UNKNOWN_PLAYBACK_CONTENT = 3907;
  SIRIUSXM_PRESETS_REQUEST_ERROR = 3908;
  SIRIUSXM_FAVORITES_REQUEST_ERROR = 3908;
  SIRIUSXM_INVALID_SESSION = 3909;
  SIRIUSXM_LOGGED_IN_ELSEWHERE = 3910;
  SIRIUSXM_NO_CONFIGURATION_DATA = 3911;
  SIRIUSXM_METADATA_REQUEST_ERROR = 3912;
  SIRIUSXM_INACTIVITY_TIMEOUT = 3913;
  SIRIUSXM_CONTENT_UNAVAILABLE = 3914;
  SIRIUSXM_UNEXPECTED_PROBLEM = 3915;
  SIRIUSXM_BYPASS_MODE_TRANSITION = 3916;
  SIRIUSXM_NEED_TO_REAUTHENTICATE = 3917;
  SIRIUSXM_AUDIO_ERROR = 3918;
  SIRIUSXM_FAVORITES_FULL = 3919;
  SIRIUSXM_FAVORITES_LOGGED_IN_ELSEWHERE = 3920;
  SIRIUSXM_SKIP_LIMIT_REACHED = 3921;
  SIRIUSXM_ONDEMAND_BYPASS_MODE_ERROR = 3922;
  SIRIUSXM_EXPIRED_ACCOUNT_ERROR = 3923;
  SIRIUSXM_EXPIRED_ONDEMAND_EPISODE = 3924;
  SIRIUSXM_ONDEMAND_CONTENT_UNAVAILABLE = 3925;
  SIRIUSXM_LAST_ERROR_CODE = 3999;
  SW_UPDATE_GENERAL_ERROR = 4000;
  SW_UPDATE_CHECK_FAILED = 4001;
  SW_UPDATE_CHECK_UNSUPPORTED_DEVICE = 4002;
  SW_UPDATE_CHECK_LOW_BATTERY = 4003;
  SW_UPDATE_CHECK_HTTP_ERROR = 4004;
  SW_UPDATE_CHECK_SERVER_XML_ERROR = 4005;
  SW_UPDATE_CHECK_NOT_ALLOWED = 4006;
  SW_UPDATE_START_NOT_ALLOWED = 4007;
  SW_UPDATE_REQUIRED = 4008;
  AMAZON_UNKNOWN_ERROR = 4100;
  AMAZON_NETWORK_ERROR = 4101;
  AMAZON_UNKNOWN_PLAYBACK_CONTENT = 4102;
  AMAZON_ACCESS_TOKEN_ERROR = 4103;
  AMAZON_RATING_REQUEST_ERROR = 4104;
  AMAZON_CONCURRENT_PLAYBACK_ERROR = 4105;
  AMAZON_TRACK_GENERAL_ERROR = 4106;
  AMAZON_CONTENT_UNAVAILABLE = 4107;
  LOCAL_MUSIC_UNKNOWN_ERROR = 4200;
  LOCAL_MUSIC_SERVER_UNEXPECTEDLY_OFFLINE = 4201;
  LOCAL_MUSIC_SERVER_UKNOWN_ERROR = 4202;
  LOCAL_MUSIC_SERVER_OFFLINE = 4203;
  LOCAL_MUSIC_TRACK_NO_LONGER_AVAILABLE = 4204;
  QPLAY_SEEK_FAILED = 4300;
  QPLAY_SKIP_NEXT_FAILED = 4301;
  QPLAY_SKIP_PREV_FAILED = 4302;
  BMX_UNKNOWN_ERROR = 4500;
  BMX_HTTP_ERROR = 4501;
  BMX_JSON_PARSE_ERROR = 4502;
  BMX_UPDATE_FAVORITE_REQUEST_ERROR = 4503;
  BMX_REFRESH_TOKEN_ERROR = 4504;
  BMX_UNKNOWN_PLAYBACK_CONTENT = 4505;
  BMX_SEEK_NOT_ALLOWED = 4506;
  BMX_SEEK_PAST_END = 4507;
  BMX_UPDATE_RATING_REQUEST_ERROR = 4508;
  NETWORK_ANALYSIS_INVALID = 5000;
  NETWORK_ANALYSIS_FULLY_WORKING = 5010;
  NETWORK_ANALYSIS_MARGE_CONNECTION_FAILURE = 5020;
  NETWORK_ANALYSIS_MARGE_IS_DOWN = 5030;
  NETWORK_ANALYSIS_INTERMITTENT_DNS = 5040;
  NETWORK_ANALYSIS_MISSING_UPLINK = 5050;
  NETWORK_ANALYSIS_WAITING_FOR_DHCP_SERVER = 5060;
  NETWORK_ANALYSIS_NETWORK_BRIDGE_DOWN = 5070;
  NETWORK_ANALYSIS_NETWORK_BRIDGE_AND_MARGE_ARE_DOWN = 5080;
  NETWORK_ANALYSIS_NETWORK_BRIDGE_DOWN_AND_MISSING_UPLINK = 5090;
  NETWORK_ANALYSIS_NETWORK_CONNECTION_LOST = 5100;
  NETWORK_ANALYSIS_SETUP_NOT_DONE = 5110;
  NETWORK_ANALYSIS_SSID_NOT_IN_RANGE = 5120;
  NETWORK_ANALYSIS_BCO_MISCOMMUNICATION = 5130;
  GROUP_MEMBER_MISSING_ERROR = 5570;
  GROUP_NO_GROUP_TO_UPDATE_ERROR = 5610;
  GROUP_MALFORMED_GROUP_REQUEST_ERROR = 5540;
  GROUP_CREATE_GROUP_ON_MARGE_ERROR = 5580;
  GROUP_NO_GROUP_TO_REMOVE_ERROR = 5550;
  GROUP_ALREADY_EXISTS_ERROR = 5510;
  GROUP_DELETE_GROUP_ON_MARGE_ERROR = 5590;
  GROUP_UNKNOWN_ERROR = 5500;
  GROUP_UPDATE_GROUP_ON_MARGE_ERROR = 5600;
  GROUP_BUSY_WITH_PREVIOUS_REQUEST_ERROR = 5560;
  SOUNDTOUCH_CLIENT_OPERATION_UNHANDLED = 5700;
  SOUNDTOUCH_CLIENT_MISSING_BODY_ELEMENT = 5701;
}
