syntax = "proto2";

package SoundTouchInterface;

import "ProtoToMarkup/MarkupOptions.proto";

enum GroupStatus {
  GROUP_UNKNOWN = 0;
  GROUP_CONNECTING = 1;
  GROUP_OK = 2;
  GROUP_OK_MARGE_ONLY = 3;
  GROUP_MARGE_REQUEST_FAILED = 4;
  GROUP_PEER_REQUEST_FAILED = 5;
  GROUP_ERROR = 99;
}

message group {
  message RoleTypes {
    enum Roles {
      NORMAL = 0;
      LEFT = 1;
      RIGHT = 2;
    }
    optional .SoundTouchInterface.group.RoleTypes.Roles text = 1;
  }
  message String {
    required string text = 1;
  }
  message GroupRole {
    optional .SoundTouchInterface.group.String deviceId = 1;
    optional .SoundTouchInterface.group.RoleTypes role = 2;
    optional .SoundTouchInterface.group.String ipAddress = 3;
  }
  message GroupRoles {
    repeated .SoundTouchInterface.group.GroupRole groupRole = 1;
  }
  message Name {
    optional string text = 1;
  }
  message Status {
    optional .SoundTouchInterface.GroupStatus text = 1;
  }
  optional string id = 1;
  optional .SoundTouchInterface.group.String name = 2;
  optional .SoundTouchInterface.group.String masterDeviceId = 3;
  optional .SoundTouchInterface.group.GroupRoles roles = 4;
  optional .SoundTouchInterface.group.String senderIPAddress = 5;
  optional .SoundTouchInterface.group.Status status = 6;
}
