# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SoundTouchInterface/Zone.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'SoundTouchInterface/Zone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ProtoToMarkup import MarkupOptions_pb2 as ProtoToMarkup_dot_MarkupOptions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSoundTouchInterface/Zone.proto\x12\x13SoundTouchInterface\x1a!ProtoToMarkup/MarkupOptions.proto\"R\n\x06Member\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tipaddress\x18\x02 \x01(\t\x12\'\n\x04role\x18\x03 \x01(\x0e\x32\x19.SoundTouchInterface.Role\"t\n\x04zone\x12\x0e\n\x06master\x18\x01 \x01(\t\x12+\n\x06member\x18\x02 \x03(\x0b\x32\x1b.SoundTouchInterface.Member\x12\x17\n\x0fsenderIPAddress\x18\x03 \x01(\t\x12\x16\n\x0esenderIsMaster\x18\x04 \x01(\x08*9\n\x04Role\x12\n\n\x06NORMAL\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x10\n\x0cINVALID_ROLE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SoundTouchInterface.Zone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=292
  _globals['_ROLE']._serialized_end=349
  _globals['_MEMBER']._serialized_start=90
  _globals['_MEMBER']._serialized_end=172
  _globals['_ZONE']._serialized_start=174
  _globals['_ZONE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
